import type { Metadata } from "next";
import "./globals.css";
import AppFooter from "@/components/AppFooter";
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const bgImages: string[] = [
    '../public/images/home-bg1.svg',
    '../public/images/bg2.svg',
    '../public/images/bg3.svg',
    '../public/images/bg4.svg',
  ];
  

  return (
    <html lang="en">
      <Provider>{children}</Provider>
    </html>
  );
}
